DELETE  http://127.0.0.1:8000/admin/categories/76 HTTP/1.1
Content-Type: : application/json
Accept: application/json
Authorization: Bearer 4|JJP7QRqV8ddkjA6p6hIa8PnsIwrUdN3thXL5wGyB

{
    "name": "thdaik",
    "parent_id": 3
}

DELETE  http://127.0.0.1:8000/admin/tags/61 HTTP/1.1
Content-Type: : application/json
Accept: application/json
Authorization: Bearer 7|J3nmrn77xwkLRUH8sInWJpTIKE1kmjPzblheBaCp

{
    "name": "dwaddaw d34r"
}
