POST  http://127.0.0.1:8000/admin/auth/signin HTTP/1.1
Content-Type: : application/json
Accept: application/json

{
    "user_name": "admin",
	"password": "admin"
}

DELETE  http://127.0.0.1:8000/admin/categories/76 HTTP/1.1
Content-Type: : application/json
Accept: application/json
Authorization: Bearer 4|JJP7QRqV8ddkjA6p6hIa8PnsIwrUdN3thXL5wGyB

{
    "name": "thdaik",
    "parent_id": 3
}

PUT  http://127.0.0.1:8000/admin/categories/93 HTTP/1.1
Content-Type: : application/json
Accept: application/json
Authorization: Bearer 1|XgwSLt2MRDa1x9XMJgLsJWnV7gNkRHWoDzdkuyMy

{
    "translations": [
        {
            "name": "test 133sDSFS",
            "language_id": 1
        },
        {
            "name": "tien tuan 3DSF3S",
            "language_id": 2
        }
    ],
	"parent_id": 3
}

POST  http://127.0.0.1:8000/admin/posts HTTP/1.1
Content-Type: : application/json
Accept: application/json
Authorization: Bearer 4|RwoJUthxkr8cWg5rCJACwfRp6bd5K0oRVk9NC8SG

{
    "translations": [
        {
            "title": "hahah",
            "excerpt": "hihi",
            "content": "hoho",
            "language_id": 1
        },
        {
            "title": "dkmm",
            "excerpt": "dkmmm",
            "content": "dkmmm",
            "language_id": 2
        }
    ],
    "image": "dawdawd/da/vipro",
    "status": "publish",
    "category_id": 3,
    "tags": [
        {
            "name": "vip"
        },
        {
            "name": "dawd awd pro"
        },
        {
            "name": "da da dad dddd"
        }
    ]
}
