DELETE  http://127.0.0.1:8000/admin/categories/76 HTTP/1.1
Content-Type: : application/json
Accept: application/json
Authorization: Bearer 4|JJP7QRqV8ddkjA6p6hIa8PnsIwrUdN3thXL5wGyB

{
    "name": "thdaik",
    "parent_id": 3
}

PUT  http://127.0.0.1:8000/admin/categories/96 HTTP/1.1
Content-Type: : application/json
Accept: application/json
Authorization: Bearer 2|ptHiolI07Ovv9U6Z5x6hRz6iO5l3R4tsmaDRHf79

{
    "translations": [
        {
            "name": "test 1",
            "language_id": 1
        },
        {
            "name": "tien tuan",
            "language_id": 2
        }
    ],
	"parent_id": 3
}
